### ISSUE TITLE
explain what the % field means

### ISSUE THREAD

**Issue by piem** [blabno/bisq-ui#164]
in the price column, the price is optionally prefixed by a percentage, but it is unclear what this rate means.

As @blabno puts it, _whenever market price changes the offer's price also adjusts by given percentage_. 

It would be nice to clarify:
 - what this rate means
 - why it can be positive, negative, null, or missing (o_O)
 - what the current market price is
 - how the current price of the offer changed

**Comment by tkulpa** [comment]
On it #167
